<html>
     <header>
   	    </header>
	    <body>
	           <p align=center> FORMULÁRIO RADIO</p>
 			

			<form action="radio.php" method="post">
				<B>Qual seu sistema operacional?</B><br><br><br>
				<input type=radio name=sistema value="Windows 7"> Windows 7 
				<input type=radio name=sistema value="Windows 10"> Windows 10
				<input type=radio name=sistema value="Linux"> Linux 
				<input type=radio name=sistema value="Mac"> IOS-Mac
				<br><br><br><br>
					<B>Qual a marca de seu monitor?</B><br><br>
					<input type=radio name=monitor value="Samsung"> Samsung 
					<input type=radio name=monitor value="LG"> LG 
					<input type=radio name=monitor value="Desconhecido"> Desconhecido
					<br><br>
							<input type=submit>
			</form>


		    </body>
</html> 
